Step 1: Import Libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestClassifier

Step 2: Load Dataset

In [2]:
df = pd.read_csv("student_performance_dataset_868.csv")

df.head()

   student_id  study_hours  attendance_percentage  previous_score pass_or_fail
0           1          8.1                     68              64         Pass
1           2         19.1                     94              27         Pass
2           3         14.9                     78              72         Pass
3           4         12.4                     42              74         Fail
4           5          4.0                     71              51         Fail

Step 3: Explore the Dataset

In [3]:
print("Shape:", df.shape)

Shape: (868, 5)

In [4]:
print("\nColumns:")
print(df.columns)

Columns:
Index(['student_id', 'study_hours', 'attendance_percentage', 'previous_score',
       'pass_or_fail'],
      dtype='str')

In [5]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
student_id               0
study_hours              0
attendance_percentage    0
previous_score           0
pass_or_fail             0
dtype: int64

In [6]:
print("\nFirst 5 Rows:")
print(df.head())

First 5 Rows:
   student_id  study_hours  attendance_percentage  previous_score pass_or_fail
0           1          8.1                     68              64         Pass
1           2         19.1                     94              27         Pass
2           3         14.9                     78              72         Pass
3           4         12.4                     42              74         Fail
4           5          4.0                     71              51         Fail

Step 4: Preprocess the Data

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["pass_or_fail"] = le.fit_transform(df["pass_or_fail"])

df.head()

,student_id,study_hours,attendance_percentage,previous_score,pass_or_fail
0,1,8.1,68,64,1
1,2,19.1,94,27,1
2,3,14.9,78,72,1
3,4,12.4,42,74,0
4,5,4.0,71,51,0

In [8]:
print(df["pass_or_fail"].value_counts())

pass_or_fail
1    521
0    347
Name: count, dtype: int64

Step 5: Create Features (X) and Target (y)

In [9]:
X = df[[
    "study_hours",
    "attendance_percentage",
    "previous_score"
]]

y = df["pass_or_fail"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

X.head()

Features Shape: (868, 3)
Target Shape: (868,)

   study_hours  attendance_percentage  previous_score
0          8.1                     68              64
1         19.1                     94              27
2         14.9                     78              72
3         12.4                     42              74
4          4.0                     71              51

Step 6: Split the Data into Training and Testing Sets

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (694, 3)
Testing Data Shape: (174, 3)

Step 7: Train the Machine Learning Model

In [11]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

Step 8: Test the Model and Calculate Accuracy

In [12]:
from sklearn.metrics import accuracy_score

# Make predictions
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")

Accuracy: 97.13 %

View Actual vs Predicted Values

In [13]:
results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred
})

results.head(10)

     Actual  Predicted
394       0          0
66        0          0
495       0          0
67        1          1
853       0          1
764       0          0
86        1          1
802       0          0
605       1          1
467       0          0